<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNGnBY8T\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNGnBY8T/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNGnBY8T.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNGnBY8T\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNGnBY8T\App_KernelDevDebugContainer([
    'container.build_hash' => 'NGnBY8T',
    'container.build_id' => '09a9fd1a',
    'container.build_time' => 1637921495,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNGnBY8T');
