<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOhHXYYd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOhHXYYd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOhHXYYd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOhHXYYd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOhHXYYd\App_KernelDevDebugContainer([
    'container.build_hash' => 'OhHXYYd',
    'container.build_id' => '440f3838',
    'container.build_time' => 1637851865,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOhHXYYd');
